[repository]
name = "hyprland-scroll-overview"
authors = ["yayuuu"]
commit_pins = [
    # Hyprland                                  hyprland-scroll-overview
    ["521ece463c4a9d3d128670688a34756805a4328f", "bb17a6caa04beb7cb8c544b837c2c455ff88c50c"], # v0.54.3
    ["39d7e209c79d451efab1b21151d5938289da838d", "ce32839f668f13316e9b51b8da4d3cfd80b806a1"], # v0.55.2
]

[scrolloverview]
description = "A scrollable overview plugin for Hyprland with optional hyprbars integration."
authors = ["yayuuu"]
output = "scrolloverview.so"
build = [
    "make all",
]
